### ISSUE TITLE
Missing icons in adriconf

### ISSUE THREAD

**Issue by LeandroStanger** [flathub/br.com.jeanhertel.adriconf#3] opened 2018-09-14 23:28 UTC
![captura de tela de 2018-09-14 20-25-32](https://user-images.githubusercontent.com/26097419/45579231-a2a4a000-b85c-11e8-8e02-4effa0b3dc8d.png)
<div align=center>

![captura de tela de 2018-09-14 21-09-27](https://user-images.githubusercontent.com/26097419/45580006-991e3680-b862-11e8-8e07-dbc3dd64f645.png)
</div>

**Comment by jlHertel** [comment] 2018-09-15 08:05
How did you installed it?
As the flatpak is not available yet, I suppose you installed using cmake.
Also note that we use icons from GTK+, so possibly you are missing some standard GTK+ icons.

**Comment by LeandroStanger** [comment] 2018-09-15 11:46
@jlHertel I installed it through the terminal
>flatpak install flathub br.com.jeanhertel.adriconf

You'll have to pack the icons as well 

@nedrichards you could help @jlHertel

**Comment by jlHertel** [comment] 2018-09-15 17:51
@LeandroStanger this is a known issue and needs to be fixed on the SDK.
So far the issue is tracked here: https://gitlab.com/freedesktop-sdk/freedesktop-sdk/issues/365
I will mark this as closed, as we can't do anything about it.

**Closed by jlHertel** 2018-09-15 17:51 UTC
